## Introduction to Python Exercises

Before you turn this problem in, make sure everything runs as expected. First, restart the kernel (in the menubar, select Kernel → Restart) and then run all cells (in the menubar, select Cell → Run All).  You can speak with others regarding the assignment but all work must be your own. 


### This is a 30 point assignment graded from answers to questions and automated tests that should be run at the bottom. Be sure to clearly label all of your answers and commit final tests at the end.  


**You may find it useful to go through the notebooks from the course materials when doing these exercises.**

In [1]:
name = "Emma Prescott"
collaborators = "Tyler Powell" #You can speak with others regarding the assignment, but all typed work must be your own.

### Installing Packages Locally
If you are working locally you will need to install *gradememaybe* at a minimum.  The code below should handle it. Uncomment (remove #s) this cell and then run it.

*If you are running the code on lab.analyticsdojo.com, please skip this next cell. 


In [63]:
#%%bash    
#conda install -y pip
#wget https://raw.githubusercontent.com/rpi-techfundamentals/fall2018-materials/master/requirements.txt
#pip install -r requirements.txt 

In [7]:
#This loads the grading software.  If you later get a "failed to import OK.py" you need to rerun.
from client.api.notebook import Notebook
ok = Notebook('hm02.ok')
_ = ok.auth(inline=True)

In [8]:
!conda uninstall -y matplotlib

Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - matplotlib




**If you attempt to fake passing the tests you will receive a 0 on the assignment and it will be considered an ethical violation.**

## Exercise-Packages

This creates an Numpy array. Numpy is a common package that we will use to work with arrays. You can read more about Numpy [here](http://www.numpy.org/). 

```
a = np.array([2,3,4])
print(a)
```

To get this to work, you will have to make sure that the numpy(np) package is installed. 


In [9]:
q1_question= """
(Q1) Verify that Numpy is installed. How did you know?  
Describe how you would you install it if it wasn't installed?
"""
#You must assign your answer to q1. 
q1_answer="""
A1. To install numpy, type...
import numpy as np
To verify numpy is installed I'd run the following test...
print(np.version)
If numpy is installed, the code should return whichever package your current device is using.
If numpy is not installed, open a new Terminal on analyticdojo and paste 
git clone https://github.com/numpy/numpy.git numpy
"""


(2) Fix the cell below so that `a` is a `numpy` array.

In [2]:
import numpy as np
a = np.array([5,6,7,8])
print(a, type(a))

[5 6 7 8] <class 'numpy.ndarray'>


In [11]:
"A2"
_ = ok.grade('q02')

(3) Create a numpy array `b` with the values `12, 13, 14, 15`.



In [3]:
b = np.arange(12,16,1)
print(b)

[12 13 14 15]


In [13]:
"A3"
_ = ok.grade('q03')

## Exercise - Operations on Variables




In [14]:
q4_question= """
(4) Describe what happens when you multiply an integer times a boolean? 
What is the resulting type? Provide examples.
"""
#You must assign your answer to q4_answer. 
q4_answer="""
A4. When you multiply an integer (x) times a boolean (True), it'll return just the integer
Example:
a = 5*True
print (a)
Returns: 5
OR 
b = 5*False
print (b)
Returns: 0
"""

In [15]:
q5_question= """
(5) Describe happens when you try to multiply an integer value times a null?
"""
#You must assign your answer to q5_answer. 
q5_answer="""
A5. When you try to multiply an interger times a null, it'll return a TypeError because you can't
multiply a integer by null
"""

(6) Take 5 to the power of 4 and assign it to a variable `c`. Then transform the variable `c` to a type `float`. 

In [16]:
c = float(5**4)

In [17]:
"A6"
_ = ok.grade('q06')

## Exercise-Lists
Hint: [This link is useful.](https://docs.python.org/3/tutorial/datastructures.html#more-on-lists) as is the process of tab completion (using tab to find available methods of an object).

(7) Create a list `elist1` with the following values `1,2,3,4,5`.<br>


In [18]:
elist1 = [1, 2, 3, 4, 5]

In [19]:
"A7"
_ = ok.grade('q07')

(8) Create a new list `elist2` by first creating a copy of `elist1` and then reversing the order.

*HINT, remember there is a specific function to copy a list.* 


In [20]:
elist2 = elist1.copy()
elist2.reverse()

In [21]:
"A8"
_ = ok.grade('q08')

(9) Create a new list `elist3` by first creating a copy of `elist1` and then adding `7, 8, 9` to the end. (Hint: Search for a different function if appending doesn't work.) 

In [22]:
elist3 = elist1.copy()
elist3.extend([7, 8, 9])

In [23]:
"A9"
_ = ok.grade('q09')

(10) Create a new list `elist4` by first creating a copy of `elist3` and then insert `6` between `5` and `7`.

In [24]:
elist4 = elist3[:]
elist4.insert(5,6)

In [25]:
"A10"
_ = ok.grade('q10')

## Exercise-Sets/Dictionary

This [link to documentation on sets](https://docs.python.org/3/tutorial/datastructures.html#sets) may be useful.

(11) Create a set `eset1` with the following values (1,2,3,4,5).


In [6]:
eset1 = {1, 2, 3, 4, 5}

In [27]:
"A11"
_ = ok.grade('q11')


(12) Create a new set `eset2` the following values (1,3,6).



In [5]:
eset2 = {1, 3, 6}

In [29]:
"A12"
_ = ok.grade('q12')

(13) Create a new set `eset3` that is `eset1-eset2`.



In [7]:
eset3 = eset1-eset2
eset3

{2, 4, 5}

In [31]:
"A13"
_ = ok.grade('q13')

(14) Create a new set `eset4` that is the union of `eset1+eset2`.


In [8]:
eset4 = eset1.union(eset2)
eset4

{1, 2, 3, 4, 5, 6}

In [33]:
"A14"
_ = ok.grade('q14')


(15) Create a new set `eset5` that includes values that are in both `eset1` and `eset2` (intersection).



In [9]:
eset5 = eset1.intersection(eset2)
eset5

{1, 3}

In [35]:
"A15"
_ = ok.grade('q15')

(16) Create a new dict `edict1` with the following keys and associated values: st1=45; st2=32; st3=40; st4=31.

*Hint: There is a good section on dictionaries [here](https://docs.python.org/3/tutorial/datastructures.html#dictionaries).


In [11]:
edict1 = {'st1':45,'st2':32, 'st3':40, 'st4':31}

In [37]:
"A16"
_ = ok.grade('q16')


(17) Create a new variable `key1` from edict1 where the *key* is `st3`.

In [12]:
key1 = edict1['st3']
key1

40

In [39]:
"A17"
_ = ok.grade('q17')

# Exercise-Numpy Array

(18) Create a new numpy array `nparray1` that is 3x3 and all the number 3 (should be integer type).



In [13]:
nparray1 = np.full((3,3), 3, dtype = int)
nparray1

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [41]:
"A18"
_ = ok.grade('q18')


(19) Create a new variable `nparray1sum` that sums all of column 0.


In [42]:
nparray1sum = np.sum(nparray1[:,0])


In [43]:
"A19"
_ = ok.grade('q19')

(20) Create a new variable `nparray1mean` that takes the average of column 0.


In [44]:
nparray1mean = np.mean(nparray1[:,0])

In [45]:
"A20"
_ = ok.grade('q20')

(21) Create a new numpy array `nparray2` that selects only column 1 of `nparray1` (all rows).


In [14]:
nparray2 = nparray1[0,:].reshape(3,1)
nparray2

array([[3],
       [3],
       [3]])

In [47]:
"A21"
_ = ok.grade('q21')

(22) Create a new numpy array `nparray3` that is equal to `nparray1` times `2` (you should not alter `nparray1`).


In [15]:
nparray3 = nparray1*2
nparray3

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [49]:
"A22"
_ = ok.grade('q22')

(23) Create a new numpy array nparray4 that is a verticle stack of `nparray1` and `nparray3`.

In [16]:
nparray4 = np.vstack([nparray1, nparray3])
nparray4

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [51]:
"A23"
_ = ok.grade('q23')

## Exercise-Pandas

For these you will need to import the iris dataset. You should find the file `iris.csv` in the main directory.  

While we showed 2 ways of importing a csv, you should use the `read_csv` method of Pandas to load the csv into a dataframe called `df`. 


In [18]:
#Load iris.csv into a Pandas dataframe here.
#Check out the first few rows with the head command. 
import pandas as pd
df = pd.read_csv('iris.csv')

(24) Create a variable `df_rows` that includes the number of rows in the `df` dataframe.

In [53]:
df_rows = df.shape[0]
print(df_rows)

150


In [54]:
"A24"
_ = ok.grade('q24')

(25) Create a new dataframe `df_train` that includes the first half of the `df` dataframe. Create a new dataframe `df_test` that includes the second half. 

In [55]:
df_train = df[0:75]
df_test = df[75:]

In [56]:
"A25"
_ = ok.grade('q25')

(26) Create a new Pandas Series `sepal_length` from the `sepal_length` column of the df dataframe.

In [19]:
sepal_length = pd.Series(df['sepal_length'])
sepal_length

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
6      4.6
7      5.0
8      4.4
9      4.9
10     5.4
11     4.8
12     4.8
13     4.3
14     5.8
15     5.7
16     5.4
17     5.1
18     5.7
19     5.1
20     5.4
21     5.1
22     4.6
23     5.1
24     4.8
25     5.0
26     5.0
27     5.2
28     5.2
29     4.7
      ... 
120    6.9
121    5.6
122    7.7
123    6.3
124    6.7
125    7.2
126    6.2
127    6.1
128    6.4
129    7.2
130    7.4
131    7.9
132    6.4
133    6.3
134    6.1
135    7.7
136    6.3
137    6.4
138    6.0
139    6.9
140    6.7
141    6.9
142    5.8
143    6.8
144    6.7
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [58]:
_ = ok.grade('q26')


(27) Using, the Iris dataset, find the mean of the `sepal_length` series in our sample and assign it to the `sepal_length_mean` variable. You should round the result to 3 digits after the decimal. 

```
#Round example
a=99.9999999999999
#For example, the following will round a to 2 digits.
b = round(a,2)   

```

In [59]:
sepal_length_mean = round(np.mean(sepal_length), 3)

In [60]:
"A27"
_ = ok.grade('q27')

## Run these Tests before Submission
This is a collection of all of the tests from the exercises above which will be used for grading.  

In [61]:
import os
_ = [ok.grade(q[:-3]) for q in os.listdir("tests") if q.startswith('q')]

## Output Answers before Submission
This will ouput answers.  

In [62]:
answers= [name, collaborators, q1_question, q1_answer, q4_question, q4_answer, q5_question, q5_answer]
with open('answers.txt', 'w') as outfile:   #The "with" incorporates an open and close of file. 
    outfile.write("\n".join(answers))